# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "390070c5a9db5554c631741fecb6c20f"
application_url = "https://a073-2800-300-6f52-21f0-ec4b-e373-390f-3bee.ngrok-free.app"
embedded = true
name = "Quotiza Connect"
handle = "quotiza-connect"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://a073-2800-300-6f52-21f0-ec4b-e373-390f-3bee.ngrok-free.app/auth/callback",
  "https://a073-2800-300-6f52-21f0-ec4b-e373-390f-3bee.ngrok-free.app/auth/shopify/callback",
  "https://a073-2800-300-6f52-21f0-ec4b-e373-390f-3bee.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quotiza2.myshopify.com"
automatically_update_urls_on_dev = true
