# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "390070c5a9db5554c631741fecb6c20f"
application_url = "https://produce-qc-usc-pre.trycloudflare.com"
embedded = true
name = "Quotiza Connect"
handle = "quotiza-connect"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://produce-qc-usc-pre.trycloudflare.com/auth/callback",
  "https://produce-qc-usc-pre.trycloudflare.com/auth/shopify/callback",
  "https://produce-qc-usc-pre.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quotiza2.myshopify.com"
automatically_update_urls_on_dev = true
